import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from '@react-oauth/google';
import  Sidebar  from "@/app/components/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
       
        <Sidebar/>

        <GoogleOAuthProvider clientId="198303287741-v6jbnbofpafpndoatoh9b8aj4d6nm227.apps.googleusercontent.com">
             {children}
      </GoogleOAuthProvider>
      
      </>
      </body>
    </html>
  );
}
