import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from '@react-oauth/google';
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
         <aside className="w-full bg-gray-100 border-r p-5 shadow-md flex flex-col justify-between">
        <div className="flex flex-col justify-between">
          
          <ul className="space-x-4 flex flex-row justify-end gap:4">
            <li>
              <Link href="/todo" className="text-black hover:text-blue-600 font-medium">
                🏠 Todo List
              </Link>
            </li>
            <li>
              <Link href="/articles" className=" text-black hover:text-blue-600 font-medium">
                📰 News
              </Link>
             </li>
             <li> 
              <Link href="/feedback" className="hover:text-blue-600 font-medium text-black" >📠FeedBack</Link>
            </li>
          </ul>
        </div>
        
      </aside>
        <GoogleOAuthProvider clientId="198303287741-v6jbnbofpafpndoatoh9b8aj4d6nm227.apps.googleusercontent.com">
             {children}
      </GoogleOAuthProvider>
      </>
      </body>
    </html>
  );
}
